version: "3.8"

services:
  postgres:
    hostname: postgres
    container_name: postgres
    networks:
      - simple_python
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=abdullah
      - POSTGRES_USER=abdullah
      - POSTGRES_PASSWORD=abdullah

  simple_python:
    hostname: simple_python
    image: simple_python:latest
    container_name: simple_python
    networks:
      - simple_python
    environment:
      - db_user=abdullah
      - db_pass=abdullah
      - db_host=postgres
      - db_name=abdullah
    depends_on:
      - postgres
    ports:
      - "5000:5000"

networks:
  simple_python:
